services:
  example-service:
    target: http://n-gate.com
    authentication:
      oauth2-introspection:
        requiredScope: [read, write]
        requiredAudience: [example.com/billing]
    routes:
      - prefix: /service-a
        rewrite: /
      - prefix: /service-a/healthz
        authentication:
          unauthorized: {}
      - prefix: /service-a/metrics
        authentication:
          unauthorized: {}
  example-service-2:
    target: https://immunkarte.de/v2
    authentication:
      oauth2-introspection:
        requiredScope: [read, write]
    routes:
      - prefix: /service-b
        rewrite: /
      - prefix: /service-b/healthz
        authentication:
          unauthorized: {}
      - prefix: /service-b/metrics
        authentication:
          unauthorized: {}

authentication:
  oauth2-introspection:
    baseUrl: http://some-host.local
