routes:
  - prefix: /web
    authorization:
      via: token
      from: cookie
      policy: enforced
    cors:
      enabled: true
      allowedOrigins:
        - https://my.domain
        - https://www.my.domain
      allowedMethods:
        - get
        - post
        - put
        - patch
        - delete
      allowedHeaders:
        - Content-Type
      exposedHeaders:
        - Content-Disposition
      allowCredentials: true
    rateLimit:
      enabled: true
      limit: 1000
      duration: 1m
    routes:
      - prefix: /my-service
        target: http://svc-my-service-app.namespace.svc.cluster.local
        rewrite: /
        routes:
          - prefix: /public-route
            rewrite: /public-route
            authorization:
              policy: allowed
            rateLimit:
              enabled: false
