{{- range $name, $service := .Values.services }}
{{- if and $service.enabled $service.backend.enabled }}
{{- with $service }}
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ template "project.fullname" $ }}-{{ $name }}
spec:
  timeoutSec: 60
  healthCheck:
    type: HTTP
    port: {{ .http.port | default 9090 }}
    checkIntervalSec: 15
    requestPath: {{ .backend.healthCheck | default "/healthz" }}
  sessionAffinity:
    affinityType: "CLIENT_IP"
  securityPolicy:
    name: {{ .backend.securityPolicy | default "default-web-policy" }}
{{- end }}
{{- end }}
{{- end }}