{{- range $name, $hpa := .Values.hpa }}
{{- if $hpa.enabled }}
{{- with $hpa }}
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "project.fullname" $ }}-{{ $name }}
  labels:
    {{ include "project.labels" $ | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "project.fullname" $ }}-{{ $name }}
  minReplicas: {{ .replicas.min }}
  maxReplicas: {{ .replicas.max }}
  metrics:
    {{ toYaml .metrics | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
