{{- if .Values.ingress.enabled }}
{{- with .Values.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "project.fullname" $ }}
  labels:
    {{ include "project.labels" $ | nindent 4 }}
    {{- if .labels }}
    {{ toYaml .labels | nindent 4 }}
    {{- end }}
  {{- if .annotations }}
  annotations:
    {{ toYaml .annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .rules }}
  rules:
    {{ toYaml .rules | nindent 4 }}
  {{- end}}
{{- end }}
{{- end }}