{{- range $name, $policy := .Values.networkPolicies }}
{{- if $policy.enabled }}
{{- with $policy }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "project.fullname" $ }}-{{ $name }}
  namespace: {{ $.Release.Namespace }}
spec:
  policyTypes:
    {{- if .ingress }}
    - Ingress
    {{- end}}
    {{- if .egress }}
    - Egress
    {{- end}}
  podSelector:
    matchLabels:
      tier: app
      release: {{ $.Release.Name }}
  {{- if .ingress }}
  {{- with .ingress }}
  ingress:
    {{- toYaml . | nindent 4 }}
  {{- end}}
  {{- end}}
  {{- if .egress }}
  {{- with .egress }}
  egress:
    {{- toYaml . | nindent 4 }}
  {{- end}}
  {{- end}}
{{- end }}
{{- end }}
{{- end }}
