{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "project.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "project.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "project.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "project.serviceAccountName" . }}
{{- end }}
