{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "project.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "project.labels" $ | nindent 4 }}
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ['use']
{{- if .Values.rbac.pspEnabled }}
  resourceNames:  [{{ template "project.fullname" . }}]
{{- end }}
{{- end }}
