{{- if .Values.serviceAccount.create }}
{{- with .Values.serviceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{ include "project.labels" $ | nindent 4 }}
  annotations:
    {{- toYaml .annotations | nindent 4 }}
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}
