services:
  example-service:
    target: http://n-gate.com
    routes:
      - prefix: /service-a
        rewrite: /
      - prefix: /service-a/healthz
        private: true
      - prefix: /service-a/metrics
        private: true
  example-service-2:
    authentication: jwt
    target: https://immunkarte.de/v2
    routes:
      - prefix: /service-b
        rewrite: /
      - prefix: /service-b/healthz
        private: true
      - prefix: /service-b/metrics
        private: true
authentication:
  jwt:
    publicKey: |-
      -----BEGIN PUBLIC KEY-----
      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEOr6rMmRRNKuZuwws/hWwFTM6ECEE
      aJGGARCJUO4UfoURl8b4JThGt8VDFKeR2i+ZxE+xh/wTBaJ/zvtSqZiNnQ==
      -----END PUBLIC KEY-----
