services:
  example-service:
    target: http://n-gate.com
    routes:
      - prefix: /service-a
        rewrite: /
      - prefix: /service-a/healthz
        private: true
      - prefix: /service-a/metrics
        private: true
  example-service-2:
    authenticated: true
    target: https://immunkarte.de/v2
    routes:
      - prefix: /service-b
        rewrite: /
      - prefix: /service-b/healthz
        private: true
      - prefix: /service-b/metrics
        private: true

authentication:
  tokens:
    reference:
      publicKey:
        source: gsm
        name: gsm-reference-token-public-key
      privateKey:
        source: gsm
        name: gsm-reference-token-private-key
    value:
      publicKey:
        source: gsm
        name: gsm-value-token-public-key
      privateKey:
        source: gsm
        name: gsm-value-token-private-key
