services:
  example-service:
    target: http://n-gate.com
    authenticated: true
    routes:
      - prefix: /service-a
        rewrite: /
      - prefix: /service-a/healthz
        private: true
      - prefix: /service-a/metrics
        private: true
  example-service-2:
    authenticated: true
    target: https://immunkarte.de/v2
    routes:
      - prefix: /service-b
        rewrite: /
      - prefix: /service-b/healthz
        private: true
      - prefix: /service-b/metrics
        private: true

secrets:
  source: file
  reference:
    publicKey: examples/key.pem
    privateKey: examples/pkey.pem
  value:
    publicKey: examples/key.pem
    privateKey: examples/pkey.pem
