services:
  example-service:
    target: http://n-gate.com
    authentication: oauth2-introspection
    routes:
      - prefix: /service-a
        rewrite: /
      - prefix: /service-a/healthz
        private: true
      - prefix: /service-a/metrics
        private: true
  example-service-2:
    target: https://immunkarte.de/v2
    authentication: oauth2-introspection
    routes:
      - prefix: /service-b
        rewrite: /
      - prefix: /service-b/healthz
        private: true
      - prefix: /service-b/metrics
        private: true

authentication:
  oauth2-introspection:
    baseUrl: some-host.local
